// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    owner_id, folder_id, name, size, mime, sha256,
    tg_message_id, tg_document_id, tg_access_hash, tg_file_reference, tg_dc_id, thumb_ref
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
RETURNING id, owner_id, folder_id, name, size, mime, sha256, tg_message_id, tg_document_id, tg_access_hash, tg_file_reference, tg_dc_id, thumb_ref, created_at, deleted_at
`

type CreateFileParams struct {
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.OwnerID,
		arg.FolderID,
		arg.Name,
		arg.Size,
		arg.Mime,
		arg.Sha256,
		arg.TgMessageID,
		arg.TgDocumentID,
		arg.TgAccessHash,
		arg.TgFileReference,
		arg.TgDcID,
		arg.ThumbRef,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.Mime,
		&i.Sha256,
		&i.TgMessageID,
		&i.TgDocumentID,
		&i.TgAccessHash,
		&i.TgFileReference,
		&i.TgDcID,
		&i.ThumbRef,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, owner_id, folder_id, name, size, mime, sha256, tg_message_id, tg_document_id, tg_access_hash, tg_file_reference, tg_dc_id, thumb_ref, created_at, deleted_at FROM files WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFile(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.Mime,
		&i.Sha256,
		&i.TgMessageID,
		&i.TgDocumentID,
		&i.TgAccessHash,
		&i.TgFileReference,
		&i.TgDcID,
		&i.ThumbRef,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteFile = `-- name: HardDeleteFile :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) HardDeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteFile, id)
	return err
}

const listDeletedFiles = `-- name: ListDeletedFiles :many
SELECT id, owner_id, folder_id, name, size, mime, sha256, tg_message_id, tg_document_id, tg_access_hash, tg_file_reference, tg_dc_id, thumb_ref, created_at, deleted_at FROM files WHERE deleted_at IS NOT NULL ORDER BY deleted_at ASC
`

func (q *Queries) ListDeletedFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, listDeletedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.Mime,
			&i.Sha256,
			&i.TgMessageID,
			&i.TgDocumentID,
			&i.TgAccessHash,
			&i.TgFileReference,
			&i.TgDcID,
			&i.ThumbRef,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT
    id, owner_id, folder_id, name, size, mime, sha256,
    tg_message_id, tg_document_id, tg_access_hash, tg_file_reference, tg_dc_id,
    CASE WHEN thumb_ref IS NULL THEN NULL ELSE '\x01'::bytea END AS thumb_ref,
    created_at, deleted_at
FROM files
WHERE owner_id = $1
  AND folder_id IS NOT DISTINCT FROM $2::uuid
  AND deleted_at IS NULL
ORDER BY name ASC
`

type ListFilesParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

type ListFilesRow struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
	CreatedAt       time.Time  `json:"created_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

// Lists files without ever reading the (TOASTed) thumbnail bytes: thumb_ref is
// collapsed to a 1-byte presence marker via IS NULL (which never detoasts), so a
// folder of images is not dragged off disk just to compute has_thumb.
func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]ListFilesRow, error) {
	rows, err := q.db.Query(ctx, listFiles, arg.OwnerID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesRow
	for rows.Next() {
		var i ListFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.Mime,
			&i.Sha256,
			&i.TgMessageID,
			&i.TgDocumentID,
			&i.TgAccessHash,
			&i.TgFileReference,
			&i.TgDcID,
			&i.ThumbRef,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFile = `-- name: MoveFile :exec
UPDATE files SET folder_id = $2::uuid WHERE id = $1 AND deleted_at IS NULL
`

type MoveFileParams struct {
	ID       uuid.UUID  `json:"id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) error {
	_, err := q.db.Exec(ctx, moveFile, arg.ID, arg.FolderID)
	return err
}

const renameFile = `-- name: RenameFile :exec
UPDATE files SET name = $2 WHERE id = $1 AND deleted_at IS NULL
`

type RenameFileParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) error {
	_, err := q.db.Exec(ctx, renameFile, arg.ID, arg.Name)
	return err
}

const searchFiles = `-- name: SearchFiles :many
SELECT
    id, owner_id, folder_id, name, size, mime, sha256,
    tg_message_id, tg_document_id, tg_access_hash, tg_file_reference, tg_dc_id,
    CASE WHEN thumb_ref IS NULL THEN NULL ELSE '\x01'::bytea END AS thumb_ref,
    created_at, deleted_at
FROM files
WHERE owner_id = $1
  AND deleted_at IS NULL
  AND (name ILIKE '%' || $2::text || '%'
       OR word_similarity($2::text, name) > 0.3)
ORDER BY
  (name ILIKE '%' || $2::text || '%') DESC,
  word_similarity($2::text, name) DESC,
  name ASC
LIMIT $3
`

type SearchFilesParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Query       string    `json:"query"`
	ResultLimit int32     `json:"result_limit"`
}

type SearchFilesRow struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
	CreatedAt       time.Time  `json:"created_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

// Fuzzy, typo-tolerant search over the owner's live file names. Direct substring
// (ILIKE) hits rank first, then trigram word-similarity hits, then name. The
// trigram GIN index backs both the ILIKE and word_similarity predicates. As with
// ListFiles, thumb_ref is collapsed to a presence marker so the (TOASTed) bytes
// are never read just to populate has_thumb.
func (q *Queries) SearchFiles(ctx context.Context, arg SearchFilesParams) ([]SearchFilesRow, error) {
	rows, err := q.db.Query(ctx, searchFiles, arg.OwnerID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFilesRow
	for rows.Next() {
		var i SearchFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.Mime,
			&i.Sha256,
			&i.TgMessageID,
			&i.TgDocumentID,
			&i.TgAccessHash,
			&i.TgFileReference,
			&i.TgDcID,
			&i.ThumbRef,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE files SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFile, id)
	return err
}

const storageUsedByOwner = `-- name: StorageUsedByOwner :one
SELECT COALESCE(sum(size), 0)::bigint FROM files
WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) StorageUsedByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, storageUsedByOwner, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateFileReference = `-- name: UpdateFileReference :exec
UPDATE files
SET tg_file_reference = $2, tg_access_hash = $3, tg_dc_id = $4
WHERE id = $1
`

type UpdateFileReferenceParams struct {
	ID              uuid.UUID `json:"id"`
	TgFileReference []byte    `json:"tg_file_reference"`
	TgAccessHash    int64     `json:"tg_access_hash"`
	TgDcID          int32     `json:"tg_dc_id"`
}

func (q *Queries) UpdateFileReference(ctx context.Context, arg UpdateFileReferenceParams) error {
	_, err := q.db.Exec(ctx, updateFileReference,
		arg.ID,
		arg.TgFileReference,
		arg.TgAccessHash,
		arg.TgDcID,
	)
	return err
}
