// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (owner_id, parent_id, name)
VALUES ($1, $2, $3)
RETURNING id, owner_id, parent_id, name, created_at
`

type CreateFolderParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	ParentID *uuid.UUID `json:"parent_id"`
	Name     string     `json:"name"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.OwnerID, arg.ParentID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, owner_id, parent_id, name, created_at FROM folders WHERE id = $1
`

func (q *Queries) GetFolder(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listAllFoldersForOwner = `-- name: ListAllFoldersForOwner :many
SELECT id, owner_id, parent_id, name, created_at FROM folders WHERE owner_id = $1 ORDER BY name ASC
`

func (q *Queries) ListAllFoldersForOwner(ctx context.Context, ownerID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listAllFoldersForOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, owner_id, parent_id, name, created_at FROM folders
WHERE owner_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
ORDER BY name ASC
`

type ListFoldersParams struct {
	OwnerID  uuid.UUID  `json:"owner_id"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolders, arg.OwnerID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFolder = `-- name: MoveFolder :exec
UPDATE folders SET parent_id = $2::uuid WHERE id = $1
`

type MoveFolderParams struct {
	ID       uuid.UUID  `json:"id"`
	ParentID *uuid.UUID `json:"parent_id"`
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) error {
	_, err := q.db.Exec(ctx, moveFolder, arg.ID, arg.ParentID)
	return err
}

const renameFolder = `-- name: RenameFolder :exec
UPDATE folders SET name = $2 WHERE id = $1
`

type RenameFolderParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) error {
	_, err := q.db.Exec(ctx, renameFolder, arg.ID, arg.Name)
	return err
}

const searchFolders = `-- name: SearchFolders :many
SELECT id, owner_id, parent_id, name, created_at FROM folders
WHERE owner_id = $1
  AND (name ILIKE '%' || $2::text || '%'
       OR word_similarity($2::text, name) > 0.3)
ORDER BY
  (name ILIKE '%' || $2::text || '%') DESC,
  word_similarity($2::text, name) DESC,
  name ASC
LIMIT $3
`

type SearchFoldersParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Query       string    `json:"query"`
	ResultLimit int32     `json:"result_limit"`
}

// Fuzzy, typo-tolerant search over the owner's folder names. Direct substring
// (ILIKE) hits rank first, then trigram word-similarity hits, then name.
func (q *Queries) SearchFolders(ctx context.Context, arg SearchFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, searchFolders, arg.OwnerID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
