// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFileGrant = `-- name: CreateFileGrant :one
INSERT INTO resource_grants (file_id, recipient_id, granted_by, permission)
VALUES ($1, $2, $3, $4)
ON CONFLICT (file_id, recipient_id) DO UPDATE SET permission = EXCLUDED.permission
RETURNING id, file_id, folder_id, recipient_id, granted_by, permission, created_at
`

type CreateFileGrantParams struct {
	FileID      *uuid.UUID `json:"file_id"`
	RecipientID uuid.UUID  `json:"recipient_id"`
	GrantedBy   uuid.UUID  `json:"granted_by"`
	Permission  string     `json:"permission"`
}

func (q *Queries) CreateFileGrant(ctx context.Context, arg CreateFileGrantParams) (ResourceGrant, error) {
	row := q.db.QueryRow(ctx, createFileGrant,
		arg.FileID,
		arg.RecipientID,
		arg.GrantedBy,
		arg.Permission,
	)
	var i ResourceGrant
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.FolderID,
		&i.RecipientID,
		&i.GrantedBy,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const createFolderGrant = `-- name: CreateFolderGrant :one
INSERT INTO resource_grants (folder_id, recipient_id, granted_by, permission)
VALUES ($1, $2, $3, $4)
ON CONFLICT (folder_id, recipient_id) DO UPDATE SET permission = EXCLUDED.permission
RETURNING id, file_id, folder_id, recipient_id, granted_by, permission, created_at
`

type CreateFolderGrantParams struct {
	FolderID    *uuid.UUID `json:"folder_id"`
	RecipientID uuid.UUID  `json:"recipient_id"`
	GrantedBy   uuid.UUID  `json:"granted_by"`
	Permission  string     `json:"permission"`
}

func (q *Queries) CreateFolderGrant(ctx context.Context, arg CreateFolderGrantParams) (ResourceGrant, error) {
	row := q.db.QueryRow(ctx, createFolderGrant,
		arg.FolderID,
		arg.RecipientID,
		arg.GrantedBy,
		arg.Permission,
	)
	var i ResourceGrant
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.FolderID,
		&i.RecipientID,
		&i.GrantedBy,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileGrant = `-- name: DeleteFileGrant :execrows
DELETE FROM resource_grants WHERE file_id = $1 AND recipient_id = $2
`

type DeleteFileGrantParams struct {
	FileID      *uuid.UUID `json:"file_id"`
	RecipientID uuid.UUID  `json:"recipient_id"`
}

func (q *Queries) DeleteFileGrant(ctx context.Context, arg DeleteFileGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileGrant, arg.FileID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFolderGrant = `-- name: DeleteFolderGrant :execrows
DELETE FROM resource_grants WHERE folder_id = $1 AND recipient_id = $2
`

type DeleteFolderGrantParams struct {
	FolderID    *uuid.UUID `json:"folder_id"`
	RecipientID uuid.UUID  `json:"recipient_id"`
}

func (q *Queries) DeleteFolderGrant(ctx context.Context, arg DeleteFolderGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFolderGrant, arg.FolderID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fileSharedToRecipient = `-- name: FileSharedToRecipient :one
WITH RECURSIVE chain AS (
    SELECT fo.id, fo.parent_id
    FROM files fi JOIN folders fo ON fo.id = fi.folder_id
    WHERE fi.id = $1
    UNION ALL
    SELECT p.id, p.parent_id FROM folders p JOIN chain c ON p.id = c.parent_id
)
SELECT EXISTS (
    SELECT 1 FROM resource_grants g WHERE g.file_id = $1 AND g.recipient_id = $2
    UNION ALL
    SELECT 1 FROM resource_grants g JOIN chain c ON g.folder_id = c.id WHERE g.recipient_id = $2
)
`

type FileSharedToRecipientParams struct {
	FileID      *uuid.UUID `json:"file_id"`
	RecipientID uuid.UUID  `json:"recipient_id"`
}

// True when the file is granted directly, or its folder (or any ancestor) is.
func (q *Queries) FileSharedToRecipient(ctx context.Context, arg FileSharedToRecipientParams) (bool, error) {
	row := q.db.QueryRow(ctx, fileSharedToRecipient, arg.FileID, arg.RecipientID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const folderSharedToRecipient = `-- name: FolderSharedToRecipient :one
WITH RECURSIVE chain AS (
    SELECT f.id, f.parent_id FROM folders f WHERE f.id = $1
    UNION ALL
    SELECT p.id, p.parent_id FROM folders p JOIN chain c ON p.id = c.parent_id
)
SELECT EXISTS (
    SELECT 1 FROM resource_grants g
    JOIN chain c ON g.folder_id = c.id
    WHERE g.recipient_id = $2
)
`

type FolderSharedToRecipientParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

// True when the folder, or any of its ancestors, is granted to the recipient.
func (q *Queries) FolderSharedToRecipient(ctx context.Context, arg FolderSharedToRecipientParams) (bool, error) {
	row := q.db.QueryRow(ctx, folderSharedToRecipient, arg.ID, arg.RecipientID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFileGrants = `-- name: ListFileGrants :many
SELECT g.id, g.file_id, g.folder_id, g.recipient_id, g.granted_by, g.permission, g.created_at, u.username AS recipient_username
FROM resource_grants g
JOIN users u ON u.id = g.recipient_id
WHERE g.file_id = $1
ORDER BY u.username
`

type ListFileGrantsRow struct {
	ID                uuid.UUID  `json:"id"`
	FileID            *uuid.UUID `json:"file_id"`
	FolderID          *uuid.UUID `json:"folder_id"`
	RecipientID       uuid.UUID  `json:"recipient_id"`
	GrantedBy         uuid.UUID  `json:"granted_by"`
	Permission        string     `json:"permission"`
	CreatedAt         time.Time  `json:"created_at"`
	RecipientUsername string     `json:"recipient_username"`
}

func (q *Queries) ListFileGrants(ctx context.Context, fileID *uuid.UUID) ([]ListFileGrantsRow, error) {
	rows, err := q.db.Query(ctx, listFileGrants, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFileGrantsRow
	for rows.Next() {
		var i ListFileGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.FolderID,
			&i.RecipientID,
			&i.GrantedBy,
			&i.Permission,
			&i.CreatedAt,
			&i.RecipientUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderFiles = `-- name: ListFolderFiles :many
SELECT
    id, owner_id, folder_id, name, size, mime, sha256,
    tg_message_id, tg_document_id, tg_access_hash, tg_file_reference, tg_dc_id,
    CASE WHEN thumb_ref IS NULL THEN NULL ELSE '\x01'::bytea END AS thumb_ref,
    created_at, deleted_at
FROM files
WHERE folder_id = $1 AND deleted_at IS NULL
ORDER BY name
`

type ListFolderFilesRow struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
	CreatedAt       time.Time  `json:"created_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

// Non-deleted files directly under a folder, not owner-scoped (see ListSubfolders).
// thumb_ref collapsed to a presence marker as in ListFiles.
func (q *Queries) ListFolderFiles(ctx context.Context, folderID *uuid.UUID) ([]ListFolderFilesRow, error) {
	rows, err := q.db.Query(ctx, listFolderFiles, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderFilesRow
	for rows.Next() {
		var i ListFolderFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.Mime,
			&i.Sha256,
			&i.TgMessageID,
			&i.TgDocumentID,
			&i.TgAccessHash,
			&i.TgFileReference,
			&i.TgDcID,
			&i.ThumbRef,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderGrants = `-- name: ListFolderGrants :many
SELECT g.id, g.file_id, g.folder_id, g.recipient_id, g.granted_by, g.permission, g.created_at, u.username AS recipient_username
FROM resource_grants g
JOIN users u ON u.id = g.recipient_id
WHERE g.folder_id = $1
ORDER BY u.username
`

type ListFolderGrantsRow struct {
	ID                uuid.UUID  `json:"id"`
	FileID            *uuid.UUID `json:"file_id"`
	FolderID          *uuid.UUID `json:"folder_id"`
	RecipientID       uuid.UUID  `json:"recipient_id"`
	GrantedBy         uuid.UUID  `json:"granted_by"`
	Permission        string     `json:"permission"`
	CreatedAt         time.Time  `json:"created_at"`
	RecipientUsername string     `json:"recipient_username"`
}

func (q *Queries) ListFolderGrants(ctx context.Context, folderID *uuid.UUID) ([]ListFolderGrantsRow, error) {
	rows, err := q.db.Query(ctx, listFolderGrants, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderGrantsRow
	for rows.Next() {
		var i ListFolderGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.FolderID,
			&i.RecipientID,
			&i.GrantedBy,
			&i.Permission,
			&i.CreatedAt,
			&i.RecipientUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedFilesForRecipient = `-- name: ListSharedFilesForRecipient :many
SELECT
    fi.id, fi.owner_id, fi.folder_id, fi.name, fi.size, fi.mime, fi.sha256,
    fi.tg_message_id, fi.tg_document_id, fi.tg_access_hash, fi.tg_file_reference, fi.tg_dc_id,
    CASE WHEN fi.thumb_ref IS NULL THEN NULL ELSE '\x01'::bytea END AS thumb_ref,
    fi.created_at, fi.deleted_at,
    u.username AS owner_username
FROM resource_grants g
JOIN files fi ON fi.id = g.file_id
JOIN users u ON u.id = fi.owner_id
WHERE g.recipient_id = $1 AND fi.deleted_at IS NULL
ORDER BY fi.name
`

type ListSharedFilesForRecipientRow struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
	CreatedAt       time.Time  `json:"created_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	OwnerUsername   string     `json:"owner_username"`
}

// Files granted directly to the recipient. As with ListFiles, thumb_ref is
// collapsed to a presence marker so the TOASTed bytes are never read here.
func (q *Queries) ListSharedFilesForRecipient(ctx context.Context, recipientID uuid.UUID) ([]ListSharedFilesForRecipientRow, error) {
	rows, err := q.db.Query(ctx, listSharedFilesForRecipient, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharedFilesForRecipientRow
	for rows.Next() {
		var i ListSharedFilesForRecipientRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.Mime,
			&i.Sha256,
			&i.TgMessageID,
			&i.TgDocumentID,
			&i.TgAccessHash,
			&i.TgFileReference,
			&i.TgDcID,
			&i.ThumbRef,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedFoldersForRecipient = `-- name: ListSharedFoldersForRecipient :many
SELECT f.id, f.owner_id, f.parent_id, f.name, f.created_at, u.username AS owner_username
FROM resource_grants g
JOIN folders f ON f.id = g.folder_id
JOIN users u ON u.id = f.owner_id
WHERE g.recipient_id = $1
ORDER BY f.name
`

type ListSharedFoldersForRecipientRow struct {
	ID            uuid.UUID  `json:"id"`
	OwnerID       uuid.UUID  `json:"owner_id"`
	ParentID      *uuid.UUID `json:"parent_id"`
	Name          string     `json:"name"`
	CreatedAt     time.Time  `json:"created_at"`
	OwnerUsername string     `json:"owner_username"`
}

func (q *Queries) ListSharedFoldersForRecipient(ctx context.Context, recipientID uuid.UUID) ([]ListSharedFoldersForRecipientRow, error) {
	rows, err := q.db.Query(ctx, listSharedFoldersForRecipient, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharedFoldersForRecipientRow
	for rows.Next() {
		var i ListSharedFoldersForRecipientRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubfolders = `-- name: ListSubfolders :many
SELECT id, owner_id, parent_id, name, created_at FROM folders WHERE parent_id = $1 ORDER BY name
`

// Children of a folder, not scoped to the caller's ownership — used inside an
// already access-checked shared folder.
func (q *Queries) ListSubfolders(ctx context.Context, parentID *uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listSubfolders, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
