// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
	CreatedAt       time.Time  `json:"created_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

type FileShare struct {
	Token     string     `json:"token"`
	FileID    uuid.UUID  `json:"file_id"`
	CreatedBy uuid.UUID  `json:"created_by"`
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at"`
}

type Folder struct {
	ID        uuid.UUID  `json:"id"`
	OwnerID   uuid.UUID  `json:"owner_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
}

type ResourceGrant struct {
	ID          uuid.UUID  `json:"id"`
	FileID      *uuid.UUID `json:"file_id"`
	FolderID    *uuid.UUID `json:"folder_id"`
	RecipientID uuid.UUID  `json:"recipient_id"`
	GrantedBy   uuid.UUID  `json:"granted_by"`
	Permission  string     `json:"permission"`
	CreatedAt   time.Time  `json:"created_at"`
}

type ResourceTag struct {
	TagID    uuid.UUID  `json:"tag_id"`
	FileID   *uuid.UUID `json:"file_id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
}

type TelegramAccount struct {
	ID                   int32     `json:"id"`
	SessionBlobEncrypted []byte    `json:"session_blob_encrypted"`
	TgUserIDHash         *string   `json:"tg_user_id_hash"`
	ChannelID            *int64    `json:"channel_id"`
	ChannelAccessHash    *int64    `json:"channel_access_hash"`
	DcID                 *int32    `json:"dc_id"`
	IsPremium            bool      `json:"is_premium"`
	Status               string    `json:"status"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type User struct {
	ID                 uuid.UUID `json:"id"`
	Username           string    `json:"username"`
	PasswordHash       string    `json:"password_hash"`
	Role               string    `json:"role"`
	CreatedAt          time.Time `json:"created_at"`
	GenerateThumbnails bool      `json:"generate_thumbnails"`
}
