// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFileTag(ctx context.Context, arg AddFileTagParams) error
	AddFolderTag(ctx context.Context, arg AddFolderTagParams) error
	CountAdmins(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFileGrant(ctx context.Context, arg CreateFileGrantParams) (ResourceGrant, error)
	CreateFileShare(ctx context.Context, arg CreateFileShareParams) (FileShare, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateFolderGrant(ctx context.Context, arg CreateFolderGrantParams) (ResourceGrant, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteFileGrant(ctx context.Context, arg DeleteFileGrantParams) (int64, error)
	// Deletes a share only when the requesting user owns the underlying file.
	// Returns the affected row count so the caller can 404 an unknown/foreign token.
	DeleteFileShareOwned(ctx context.Context, arg DeleteFileShareOwnedParams) (int64, error)
	DeleteFolder(ctx context.Context, id uuid.UUID) error
	DeleteFolderGrant(ctx context.Context, arg DeleteFolderGrantParams) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	// True when the file is granted directly, or its folder (or any ancestor) is.
	FileSharedToRecipient(ctx context.Context, arg FileSharedToRecipientParams) (bool, error)
	// True when the folder, or any of its ancestors, is granted to the recipient.
	FolderSharedToRecipient(ctx context.Context, arg FolderSharedToRecipientParams) (bool, error)
	GetFile(ctx context.Context, id uuid.UUID) (File, error)
	GetFolder(ctx context.Context, id uuid.UUID) (Folder, error)
	GetSessionUser(ctx context.Context, id string) (GetSessionUserRow, error)
	// Resolves a share token to its (live) file row, plus the share's expiry so the
	// caller can reject an expired link. Soft-deleted files are excluded, so their
	// links 404.
	GetShareFile(ctx context.Context, token string) (GetShareFileRow, error)
	GetTag(ctx context.Context, id uuid.UUID) (Tag, error)
	GetTelegramAccount(ctx context.Context) (TelegramAccount, error)
	GetTelegramSessionBlob(ctx context.Context) ([]byte, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	HardDeleteFile(ctx context.Context, id uuid.UUID) error
	ListAllFoldersForOwner(ctx context.Context, ownerID uuid.UUID) ([]Folder, error)
	ListDeletedFiles(ctx context.Context) ([]File, error)
	ListFileGrants(ctx context.Context, fileID *uuid.UUID) ([]ListFileGrantsRow, error)
	ListFileSharesByFile(ctx context.Context, fileID uuid.UUID) ([]FileShare, error)
	// Lists files without ever reading the (TOASTed) thumbnail bytes: thumb_ref is
	// collapsed to a 1-byte presence marker via IS NULL (which never detoasts), so a
	// folder of images is not dragged off disk just to compute has_thumb.
	ListFiles(ctx context.Context, arg ListFilesParams) ([]ListFilesRow, error)
	// Non-deleted files directly under a folder, not owner-scoped (see ListSubfolders).
	// thumb_ref collapsed to a presence marker as in ListFiles.
	ListFolderFiles(ctx context.Context, folderID *uuid.UUID) ([]ListFolderFilesRow, error)
	ListFolderGrants(ctx context.Context, folderID *uuid.UUID) ([]ListFolderGrantsRow, error)
	ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error)
	// Users (id + username only) the caller can share with: everyone but themselves.
	ListShareableUsers(ctx context.Context, id uuid.UUID) ([]ListShareableUsersRow, error)
	// Files granted directly to the recipient. As with ListFiles, thumb_ref is
	// collapsed to a presence marker so the TOASTed bytes are never read here.
	ListSharedFilesForRecipient(ctx context.Context, recipientID uuid.UUID) ([]ListSharedFilesForRecipientRow, error)
	ListSharedFoldersForRecipient(ctx context.Context, recipientID uuid.UUID) ([]ListSharedFoldersForRecipientRow, error)
	// Children of a folder, not scoped to the caller's ownership — used inside an
	// already access-checked shared folder.
	ListSubfolders(ctx context.Context, parentID *uuid.UUID) ([]Folder, error)
	// Every (tag -> file/folder) assignment for the owner's tags — drives the
	// client-side tag-badge lookup across listings.
	ListTagAssignments(ctx context.Context, ownerID uuid.UUID) ([]ResourceTag, error)
	ListTagFiles(ctx context.Context, tagID uuid.UUID) ([]ListTagFilesRow, error)
	ListTagFolders(ctx context.Context, tagID uuid.UUID) ([]Folder, error)
	// Owner's tags with how many live items carry each (for the sidebar list).
	// Soft-deleted files keep their resource_tags row (a soft delete is an UPDATE,
	// so the ON DELETE CASCADE never fires), so they must be excluded from the count;
	// folders are hard-deleted, so their associations cascade away and always count.
	ListTags(ctx context.Context, ownerID uuid.UUID) ([]ListTagsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	MoveFile(ctx context.Context, arg MoveFileParams) error
	MoveFolder(ctx context.Context, arg MoveFolderParams) error
	RemoveFileTag(ctx context.Context, arg RemoveFileTagParams) (int64, error)
	RemoveFolderTag(ctx context.Context, arg RemoveFolderTagParams) (int64, error)
	RenameFile(ctx context.Context, arg RenameFileParams) error
	RenameFolder(ctx context.Context, arg RenameFolderParams) error
	ResetTelegramAccount(ctx context.Context) error
	// Fuzzy, typo-tolerant search over the owner's live file names. Direct substring
	// (ILIKE) hits rank first, then trigram word-similarity hits, then name. The
	// trigram GIN index backs both the ILIKE and word_similarity predicates. As with
	// ListFiles, thumb_ref is collapsed to a presence marker so the (TOASTed) bytes
	// are never read just to populate has_thumb.
	SearchFiles(ctx context.Context, arg SearchFilesParams) ([]SearchFilesRow, error)
	// Fuzzy, typo-tolerant search over the owner's folder names. Direct substring
	// (ILIKE) hits rank first, then trigram word-similarity hits, then name.
	SearchFolders(ctx context.Context, arg SearchFoldersParams) ([]Folder, error)
	SetTelegramLinked(ctx context.Context, arg SetTelegramLinkedParams) error
	SetTelegramSessionBlob(ctx context.Context, sessionBlobEncrypted []byte) error
	SetUserGenerateThumbnails(ctx context.Context, arg SetUserGenerateThumbnailsParams) error
	SoftDeleteFile(ctx context.Context, id uuid.UUID) error
	StorageUsedByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	UpdateFileReference(ctx context.Context, arg UpdateFileReferenceParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
