// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFileShare = `-- name: CreateFileShare :one
INSERT INTO file_shares (token, file_id, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token, file_id, created_by, created_at, expires_at
`

type CreateFileShareParams struct {
	Token     string     `json:"token"`
	FileID    uuid.UUID  `json:"file_id"`
	CreatedBy uuid.UUID  `json:"created_by"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) CreateFileShare(ctx context.Context, arg CreateFileShareParams) (FileShare, error) {
	row := q.db.QueryRow(ctx, createFileShare,
		arg.Token,
		arg.FileID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i FileShare
	err := row.Scan(
		&i.Token,
		&i.FileID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteFileShareOwned = `-- name: DeleteFileShareOwned :execrows
DELETE FROM file_shares
USING files
WHERE file_shares.token = $1
  AND file_shares.file_id = files.id
  AND files.owner_id = $2
`

type DeleteFileShareOwnedParams struct {
	Token   string    `json:"token"`
	OwnerID uuid.UUID `json:"owner_id"`
}

// Deletes a share only when the requesting user owns the underlying file.
// Returns the affected row count so the caller can 404 an unknown/foreign token.
func (q *Queries) DeleteFileShareOwned(ctx context.Context, arg DeleteFileShareOwnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileShareOwned, arg.Token, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShareFile = `-- name: GetShareFile :one
SELECT f.id, f.owner_id, f.folder_id, f.name, f.size, f.mime, f.sha256, f.tg_message_id, f.tg_document_id, f.tg_access_hash, f.tg_file_reference, f.tg_dc_id, f.thumb_ref, f.created_at, f.deleted_at, f.enc_iv, s.expires_at AS share_expires_at
FROM file_shares s
JOIN files f ON f.id = s.file_id
WHERE s.token = $1 AND f.deleted_at IS NULL
`

type GetShareFileRow struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
	CreatedAt       time.Time  `json:"created_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	EncIv           []byte     `json:"enc_iv"`
	ShareExpiresAt  *time.Time `json:"share_expires_at"`
}

// Resolves a share token to its (live) file row, plus the share's expiry so the
// caller can reject an expired link. Soft-deleted files are excluded, so their
// links 404.
func (q *Queries) GetShareFile(ctx context.Context, token string) (GetShareFileRow, error) {
	row := q.db.QueryRow(ctx, getShareFile, token)
	var i GetShareFileRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.Mime,
		&i.Sha256,
		&i.TgMessageID,
		&i.TgDocumentID,
		&i.TgAccessHash,
		&i.TgFileReference,
		&i.TgDcID,
		&i.ThumbRef,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.EncIv,
		&i.ShareExpiresAt,
	)
	return i, err
}

const listFileSharesByFile = `-- name: ListFileSharesByFile :many
SELECT token, file_id, created_by, created_at, expires_at FROM file_shares WHERE file_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFileSharesByFile(ctx context.Context, fileID uuid.UUID) ([]FileShare, error) {
	rows, err := q.db.Query(ctx, listFileSharesByFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileShare
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(
			&i.Token,
			&i.FileID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileSharesByOwner = `-- name: ListFileSharesByOwner :many
SELECT f.id, f.owner_id, f.folder_id, f.name, f.size, f.mime, f.sha256, f.tg_message_id, f.tg_document_id, f.tg_access_hash, f.tg_file_reference, f.tg_dc_id, f.thumb_ref, f.created_at, f.deleted_at, f.enc_iv, s.token AS share_token, s.created_at AS share_created_at, s.expires_at AS share_expires_at
FROM file_shares s
JOIN files f ON f.id = s.file_id
WHERE s.created_by = $1 AND f.deleted_at IS NULL
ORDER BY s.created_at DESC
`

type ListFileSharesByOwnerRow struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
	CreatedAt       time.Time  `json:"created_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	EncIv           []byte     `json:"enc_iv"`
	ShareToken      string     `json:"share_token"`
	ShareCreatedAt  time.Time  `json:"share_created_at"`
	ShareExpiresAt  *time.Time `json:"share_expires_at"`
}

// Every share link the user created, newest link first, joined to its live file
// so the caller can render the target. Soft-deleted files are excluded, matching
// the public lookup. A file shared more than once yields one row per link.
func (q *Queries) ListFileSharesByOwner(ctx context.Context, createdBy uuid.UUID) ([]ListFileSharesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listFileSharesByOwner, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFileSharesByOwnerRow
	for rows.Next() {
		var i ListFileSharesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.Mime,
			&i.Sha256,
			&i.TgMessageID,
			&i.TgDocumentID,
			&i.TgAccessHash,
			&i.TgFileReference,
			&i.TgDcID,
			&i.ThumbRef,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.EncIv,
			&i.ShareToken,
			&i.ShareCreatedAt,
			&i.ShareExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
