// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFileTag = `-- name: AddFileTag :exec
INSERT INTO resource_tags (tag_id, file_id) VALUES ($1, $2)
ON CONFLICT (tag_id, file_id) DO NOTHING
`

type AddFileTagParams struct {
	TagID  uuid.UUID  `json:"tag_id"`
	FileID *uuid.UUID `json:"file_id"`
}

func (q *Queries) AddFileTag(ctx context.Context, arg AddFileTagParams) error {
	_, err := q.db.Exec(ctx, addFileTag, arg.TagID, arg.FileID)
	return err
}

const addFolderTag = `-- name: AddFolderTag :exec
INSERT INTO resource_tags (tag_id, folder_id) VALUES ($1, $2)
ON CONFLICT (tag_id, folder_id) DO NOTHING
`

type AddFolderTagParams struct {
	TagID    uuid.UUID  `json:"tag_id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) AddFolderTag(ctx context.Context, arg AddFolderTagParams) error {
	_, err := q.db.Exec(ctx, addFolderTag, arg.TagID, arg.FolderID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (owner_id, name, color) VALUES ($1, $2, $3)
RETURNING id, owner_id, name, color, created_at
`

type CreateTagParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
	Color   string    `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.OwnerID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, owner_id, name, color, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listTagAssignments = `-- name: ListTagAssignments :many
SELECT rt.tag_id, rt.file_id, rt.folder_id
FROM resource_tags rt
JOIN tags t ON t.id = rt.tag_id
WHERE t.owner_id = $1
`

// Every (tag -> file/folder) assignment for the owner's tags — drives the
// client-side tag-badge lookup across listings.
func (q *Queries) ListTagAssignments(ctx context.Context, ownerID uuid.UUID) ([]ResourceTag, error) {
	rows, err := q.db.Query(ctx, listTagAssignments, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceTag
	for rows.Next() {
		var i ResourceTag
		if err := rows.Scan(&i.TagID, &i.FileID, &i.FolderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagFiles = `-- name: ListTagFiles :many
SELECT
    fi.id, fi.owner_id, fi.folder_id, fi.name, fi.size, fi.mime, fi.sha256,
    fi.tg_message_id, fi.tg_document_id, fi.tg_access_hash, fi.tg_file_reference, fi.tg_dc_id,
    CASE WHEN fi.thumb_ref IS NULL THEN NULL ELSE '\x01'::bytea END AS thumb_ref,
    fi.created_at, fi.deleted_at
FROM resource_tags rt
JOIN files fi ON fi.id = rt.file_id
WHERE rt.tag_id = $1 AND fi.deleted_at IS NULL
ORDER BY fi.name
`

type ListTagFilesRow struct {
	ID              uuid.UUID  `json:"id"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	FolderID        *uuid.UUID `json:"folder_id"`
	Name            string     `json:"name"`
	Size            int64      `json:"size"`
	Mime            string     `json:"mime"`
	Sha256          string     `json:"sha256"`
	TgMessageID     int64      `json:"tg_message_id"`
	TgDocumentID    int64      `json:"tg_document_id"`
	TgAccessHash    int64      `json:"tg_access_hash"`
	TgFileReference []byte     `json:"tg_file_reference"`
	TgDcID          int32      `json:"tg_dc_id"`
	ThumbRef        []byte     `json:"thumb_ref"`
	CreatedAt       time.Time  `json:"created_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

func (q *Queries) ListTagFiles(ctx context.Context, tagID uuid.UUID) ([]ListTagFilesRow, error) {
	rows, err := q.db.Query(ctx, listTagFiles, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagFilesRow
	for rows.Next() {
		var i ListTagFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.Mime,
			&i.Sha256,
			&i.TgMessageID,
			&i.TgDocumentID,
			&i.TgAccessHash,
			&i.TgFileReference,
			&i.TgDcID,
			&i.ThumbRef,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagFolders = `-- name: ListTagFolders :many
SELECT f.id, f.owner_id, f.parent_id, f.name, f.created_at FROM resource_tags rt
JOIN folders f ON f.id = rt.folder_id
WHERE rt.tag_id = $1
ORDER BY f.name
`

func (q *Queries) ListTagFolders(ctx context.Context, tagID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listTagFolders, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.owner_id, t.name, t.color, t.created_at, COUNT(rt.tag_id) AS item_count
FROM tags t
LEFT JOIN resource_tags rt ON rt.tag_id = t.id
    AND (rt.file_id IS NULL OR EXISTS (
        SELECT 1 FROM files f WHERE f.id = rt.file_id AND f.deleted_at IS NULL))
WHERE t.owner_id = $1
GROUP BY t.id
ORDER BY t.name
`

type ListTagsRow struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	ItemCount int64     `json:"item_count"`
}

// Owner's tags with how many live items carry each (for the sidebar list).
// Soft-deleted files keep their resource_tags row (a soft delete is an UPDATE,
// so the ON DELETE CASCADE never fires), so they must be excluded from the count;
// folders are hard-deleted, so their associations cascade away and always count.
func (q *Queries) ListTags(ctx context.Context, ownerID uuid.UUID) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFileTag = `-- name: RemoveFileTag :execrows
DELETE FROM resource_tags WHERE tag_id = $1 AND file_id = $2
`

type RemoveFileTagParams struct {
	TagID  uuid.UUID  `json:"tag_id"`
	FileID *uuid.UUID `json:"file_id"`
}

func (q *Queries) RemoveFileTag(ctx context.Context, arg RemoveFileTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFileTag, arg.TagID, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeFolderTag = `-- name: RemoveFolderTag :execrows
DELETE FROM resource_tags WHERE tag_id = $1 AND folder_id = $2
`

type RemoveFolderTagParams struct {
	TagID    uuid.UUID  `json:"tag_id"`
	FolderID *uuid.UUID `json:"folder_id"`
}

func (q *Queries) RemoveFolderTag(ctx context.Context, arg RemoveFolderTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFolderTag, arg.TagID, arg.FolderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags SET name = $2, color = $3 WHERE id = $1
`

type UpdateTagParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Color string    `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.Exec(ctx, updateTag, arg.ID, arg.Name, arg.Color)
	return err
}
