// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram.sql

package dbsqlc

import (
	"context"
)

const getTelegramAccount = `-- name: GetTelegramAccount :one
SELECT id, session_blob_encrypted, tg_user_id_hash, channel_id, channel_access_hash, dc_id, is_premium, status, updated_at FROM telegram_account WHERE id = 1
`

func (q *Queries) GetTelegramAccount(ctx context.Context) (TelegramAccount, error) {
	row := q.db.QueryRow(ctx, getTelegramAccount)
	var i TelegramAccount
	err := row.Scan(
		&i.ID,
		&i.SessionBlobEncrypted,
		&i.TgUserIDHash,
		&i.ChannelID,
		&i.ChannelAccessHash,
		&i.DcID,
		&i.IsPremium,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelegramSessionBlob = `-- name: GetTelegramSessionBlob :one
SELECT session_blob_encrypted FROM telegram_account WHERE id = 1
`

func (q *Queries) GetTelegramSessionBlob(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTelegramSessionBlob)
	var session_blob_encrypted []byte
	err := row.Scan(&session_blob_encrypted)
	return session_blob_encrypted, err
}

const resetTelegramAccount = `-- name: ResetTelegramAccount :exec
UPDATE telegram_account
SET session_blob_encrypted = NULL,
    tg_user_id_hash        = NULL,
    channel_id             = NULL,
    channel_access_hash    = NULL,
    dc_id                  = NULL,
    is_premium             = false,
    status                 = 'not_linked',
    updated_at             = now()
WHERE id = 1
`

func (q *Queries) ResetTelegramAccount(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetTelegramAccount)
	return err
}

const setTelegramLinked = `-- name: SetTelegramLinked :exec
UPDATE telegram_account
SET tg_user_id_hash     = $1,
    channel_id          = $2,
    channel_access_hash = $3,
    dc_id               = $4,
    is_premium          = $5,
    status              = 'linked',
    updated_at          = now()
WHERE id = 1
`

type SetTelegramLinkedParams struct {
	TgUserIDHash      *string `json:"tg_user_id_hash"`
	ChannelID         *int64  `json:"channel_id"`
	ChannelAccessHash *int64  `json:"channel_access_hash"`
	DcID              *int32  `json:"dc_id"`
	IsPremium         bool    `json:"is_premium"`
}

func (q *Queries) SetTelegramLinked(ctx context.Context, arg SetTelegramLinkedParams) error {
	_, err := q.db.Exec(ctx, setTelegramLinked,
		arg.TgUserIDHash,
		arg.ChannelID,
		arg.ChannelAccessHash,
		arg.DcID,
		arg.IsPremium,
	)
	return err
}

const setTelegramSessionBlob = `-- name: SetTelegramSessionBlob :exec
UPDATE telegram_account
SET session_blob_encrypted = $1,
    updated_at = now()
WHERE id = 1
`

func (q *Queries) SetTelegramSessionBlob(ctx context.Context, sessionBlobEncrypted []byte) error {
	_, err := q.db.Exec(ctx, setTelegramSessionBlob, sessionBlobEncrypted)
	return err
}
