package eu.r3pr3ss10n.hangar.ui.theme

import androidx.compose.ui.graphics.Color

// Brand fallback palette (used below Android 12, where Monet/dynamic color is
// unavailable). A calm blue-forward Material 3 scheme.
val md_light_primary = Color(0xFF38618C)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFD3E3FF)
val md_light_onPrimaryContainer = Color(0xFF001C3A)
val md_light_secondary = Color(0xFF545F71)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFD8E3F8)
val md_light_onSecondaryContainer = Color(0xFF111C2B)
val md_light_tertiary = Color(0xFF6C5677)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFF5D9FF)
val md_light_onTertiaryContainer = Color(0xFF261431)
val md_light_background = Color(0xFFFDFCFF)
val md_light_onBackground = Color(0xFF1A1C1E)
val md_light_surface = Color(0xFFFDFCFF)
val md_light_onSurface = Color(0xFF1A1C1E)
val md_light_surfaceVariant = Color(0xFFDFE2EB)
val md_light_onSurfaceVariant = Color(0xFF43474E)
val md_light_outline = Color(0xFF73777F)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)

val md_dark_primary = Color(0xFFA3C9FE)
val md_dark_onPrimary = Color(0xFF00315E)
val md_dark_primaryContainer = Color(0xFF1C4873)
val md_dark_onPrimaryContainer = Color(0xFFD3E3FF)
val md_dark_secondary = Color(0xFFBCC7DC)
val md_dark_onSecondary = Color(0xFF263141)
val md_dark_secondaryContainer = Color(0xFF3C4758)
val md_dark_onSecondaryContainer = Color(0xFFD8E3F8)
val md_dark_tertiary = Color(0xFFD9BDE3)
val md_dark_onTertiary = Color(0xFF3C2947)
val md_dark_tertiaryContainer = Color(0xFF533F5F)
val md_dark_onTertiaryContainer = Color(0xFFF5D9FF)
val md_dark_background = Color(0xFF1A1C1E)
val md_dark_onBackground = Color(0xFFE3E2E6)
val md_dark_surface = Color(0xFF1A1C1E)
val md_dark_onSurface = Color(0xFFE3E2E6)
val md_dark_surfaceVariant = Color(0xFF43474E)
val md_dark_onSurfaceVariant = Color(0xFFC3C7CF)
val md_dark_outline = Color(0xFF8D9199)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
